### ISSUE TITLE
New scripts added to documents do not execute

### ISSUE THREAD

**Issue by waqas-tio** [hasharray/liveflow.js#27]
Hi ,

I have tried demo https://thingamajig.js.org/ but code withing anonymus function / withing document ready block did not work.

(function() {
   document.querySelector('span').innerHTML = "aaaaaaaaaaaaaaa";
})();

**Comment by caspervonb** [comment]
Call expressions (function calls) only execute again if their parameters are changed, changing a function body does not invalidate a past function call so it won't execute again.

Think about it as if you were changing a callback, you don't want new timers every time you change the timer callback, that's the rationale for this case anyhow.

Workaround to force something to execute again: comment -> save -> uncomment -> save.

**Comment by waqas-tio** [comment]
What about code within this block

$( document ).ready(function() {
     document.getElementById('btid').onclick = alertMe();
});


Any thing in above block does not gets updated by thingamajig.js

**Comment by caspervonb** [comment]
That should, as jQuery is smart enough to check if `document.readyState` is already interactive in `$(document).ready`.

This is due to incomplete DOM merging implementation basically, so its a bug. It isn't currently dealing quite correctly with loading new scripts.

Appreciate the report.

**Comment by waqas-tio** [comment]
Thanks,
I am interested to see the solution to this bug.
Could you please inform me how / when you resolved this bug.

Many thanks

**Comment by caspervonb** [comment]
This particular issue is due to how innerHTML works, the spec states that any `<script>` tag inserted via innerHTML shall not execute under any circumstances and I have not gotten around to implementing it properly yet, have my hands full with the script execution engine.

Workaround, is don't use innerHTML, or at the very-least make sure to replace any <script> tags with new clones that you intend to have execute.

**Comment by caspervonb** [comment]
Fixed in https://github.com/hasharray/liveflow.js/commit/ce01b772e6a94fbe70962c85668bf489e9ba4f4c
